In [5]:
import os
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import time
from pprint import pprint
import urllib.request as ur

#pd.set_option('display.max_columns', 500)
#csv = requests.get("http://site-ftp.site.com/test/cat/filename.csv")
url="ftp://ftp.ncdc.noaa.gov/pub/data/ghcn/v3/csv/ghcnm.tavg.v3.3.0.20181219.qcu.dat.csv"
req = ur.Request(url) 
csvfile = ur.urlopen(req)

####################
# Warning
####################
#due to file size over 120M, this step will take over 5 minutes to show result.
df = pd.read_csv(csvfile, header=None)
print(df)

                 0     1     2     3  4  5  6     7  8  9  ... 41  42    43  \
0       10160355000  1878  TAVG   890        1   950       ...  S   1  1370
1       10160355000  1879  TAVG  1180        1  1170       ...      1  1450
2       10160355000  1880  TAVG   960        1  1110       ...      1  1570
3       10160355000  1931  TAVG -9999            970       ...      1  1550
4       10160355000  1932  TAVG  1010        1   980       ...        -9999
5       10160355000  1933  TAVG -9999          -9999       ...      1  1480
6       10160355000  1934  TAVG  1030        1   970       ...      1  1470
7       10160355000  1935  TAVG   860        1  1090       ...         1490
8       10160355000  1936  TAVG  1310        1  1380       ...      1  1410
9       10160355000  1937  TAVG  1200        1  1250       ...      1  1700
10      10160355000  1938  TAVG  1060        1   900       ...      1  1560
11      10160355000  1939  TAVG  1280        1  1180       ...      1  1530
12      10160355000  1940  TAVG  1110        1  1300       ...      1  1450
13      10160355000  1941  TAVG  1150        1 -9999       ...        -9999
14      10160355000  1966  TAVG -9999          -9999       ...         1330
15      10160355000  1967  TAVG  1000        0  1120       ...      0  1660
16      10160355000  1968  TAVG  1090        0  1230       ...      0  1620
17      10160355000  1969  TAVG  1170        0  1140       ...      0  1610
18      10160355000  1970  TAVG  1290        0  1100       ...  S   0  1480
19      10160355000  1971  TAVG  1160        0  1040       ...      0  1330
20      10160355000  1972  TAVG  1010        0  1280       ...      0  1540
21      10160355000  1973  TAVG  1120        0  1010       ...      0  1400
22      10160355000  1974  TAVG  1220        0  1180       ...      0  1410
23      10160355000  1975  TAVG  1150        0  1090       ...         1390
24      10160355000  1976  TAVG  1020        0  1080       ...         1290
25      10160355000  1977  TAVG  1260        0  1290       ...         1540
26      10160355000  1978  TAVG   990        0  1340       ...      0  1280
27      10160355000  1979  TAVG  1370        0  1280       ...      0  1310
28      10160355000  1980  TAVG  1080        0  1160       ...      0  1550
29      10160355000  1981  TAVG   980        0  1090       ...      0  1460
...             ...   ...   ...   ... .. .. ..   ... .. .. ... ..  ..   ...
471035  80099912001  1980  TAVG   460        0   530       ...      0   770
471036  80099912001  1981  TAVG   710        0   600       ...        -9999
471037  80099913001  1975  TAVG -9999          -9999       ...      G -9999
471038  80099913001  1976  TAVG -9999           1090       ...      G  1220
471039  80099913001  1977  TAVG  1010        G  1070       ...      G  1280
471040  80099913001  1978  TAVG  1030        G  1100       ...      G  1400
471041  80099913001  1979  TAVG  1040        G  1110       ...      G  1370
471042  80099913001  1980  TAVG  1100        G  1100       ...      G  1290
471043  80099913001  1981  TAVG  1210        G  1100       ...      G  1430
471044  80099913001  1982  TAVG  1210        G -9999       ...      G  1200
471045  80099913001  1983  TAVG  1160        G  1050       ...      G  1410
471046  80099913001  1984  TAVG  1100        G  1110       ...      G  1220
471047  80099913001  1985  TAVG  1110        G  1110       ...      G  1290
471048  80099914001  1955  TAVG -9999          -9999       ...      G  2030
471049  80099914001  1956  TAVG  1560        G  1460       ...      G  2030
471050  80099914001  1957  TAVG  1370        G  1360       ...      G  1930
471051  80099914001  1958  TAVG  1500        G  1370       ...      G  2080
471052  80099914001  1959  TAVG  1550        G  1420       ...      G  1820
471053  80099914001  1960  TAVG  1470        G  1410       ...      G  1990
471054  80099914001  1961  TAVG  1460        G  1410       ...      G  2010
471055  80099914001  1962  TAVG  1490        G  1410       ...      G  2040
471056  80099914001  1963  TAVG  1580        G  1290       ...      G  1940
471057  80099914001  1964  TAVG  1480        G  1230       ...      G  1940
471058  80099914001  1965  TAVG  1420        G  1410       ...      G  1960
471059  80099914001  1966  TAVG  1430        G  1460       ...      G  1920
471060  80099914001  1967  TAVG  1520        G  1440       ...      G  1850
471061  80099914001  1968  TAVG  1430        G  1230       ...      G  1860
471062  80099914001  1969  TAVG  1590        G  1510       ...      G  1830
471063  80099914001  1970  TAVG  1410        G  1360       ...      G  1960
471064  80099914001  1971  TAVG  1500        G  1280       ...      G  2000

       44 45  46    47 48 49  50
0              1  1150         1
1              1   900         1
2              1  1290         1
3              1  1060         1
4                -9999
5              1  1130         1
6              1  1330         1
7              1  1250         1
8              1  1080         1
9              1  1100         1
10             1  1230         1
11             1  1250         1
12             1  1080         1
13               -9999
14             0  1100         0
15             0  1070         0
16             0  1280         0
17             0  1080         0
18             0  1140         0
19             0  1120         0
20             0  1190         0
21             0  1210         0
22             0 -9999
23             0  1180         0
24             0  1280         0
25             0  1240         0
26             0  1410         0
27             0  1170         0
28             0   990         0
29             0  1540         0
...    .. ..  ..   ... .. ..  ..
471035         0   650         0
471036           -9999
471037            1130         G
471038         G  1030         G
471039         G  1210         G
471040         G  1150         G
471041         G  1220         G
471042         G  1240         G
471043         G  1210         G
471044         G  1120         G
471045         G  1230         G
471046         G  1190         G
471047         G  1250         G
471048         G  1700         G
471049         G  1490     O   G
471050         G  1840         G
471051         G  1690         G
471052         G  1740         G
471053         G  1760         G
471054         G  1590         G
471055         G  1690         G
471056         G  1690         G
471057         G  1520         G
471058         G  1720         G
471059         G  1690         G
471060         G  1700         G
471061         G  1720         G
471062         G -9999
471063         G  1650         G
471064         G  1700         G

[471065 rows x 51 columns]

In [6]:
#drop columns, specify axis=1 for columns and axis=0 for rows
df.drop(df.columns[[4,5,6,8,9,10,12,13,14,16,17,18,20,21,22,24,25,26,28,29,30,
                    32,33,34,36,37,38,40,41,42,44,45,46,48,49,50]], axis=1, inplace=True)
print(df)

                 0     1     2     3     7     11    15    19    23    27  \
0       10160355000  1878  TAVG   890   950  1110  1610  1980  2240  2490
1       10160355000  1879  TAVG  1180  1170  1220  1550  1560  2270  2400
2       10160355000  1880  TAVG   960  1110  1240  1520  1710  2070  2580
3       10160355000  1931  TAVG -9999   970 -9999 -9999  1850  2390 -9999
4       10160355000  1932  TAVG  1010   980 -9999  1420  1840 -9999  2290
5       10160355000  1933  TAVG -9999 -9999 -9999 -9999  1870 -9999 -9999
6       10160355000  1934  TAVG  1030   970  1190  1550  1760 -9999  2450
7       10160355000  1935  TAVG   860  1090  1220  1500 -9999  2150 -9999
8       10160355000  1936  TAVG  1310  1380  1360  1550  1320  1950  2370
9       10160355000  1937  TAVG  1200  1250  1450  1470 -9999  2200  2320
10      10160355000  1938  TAVG  1060   900  1100  1320  1680  2160  2390
11      10160355000  1939  TAVG  1280  1180  1160  1470  1550  2010  2390
12      10160355000  1940  TAVG  1110  1300  1430  1470  1740  2000  2250
13      10160355000  1941  TAVG  1150 -9999  1400  1570 -9999 -9999 -9999
14      10160355000  1966  TAVG -9999 -9999 -9999 -9999 -9999 -9999 -9999
15      10160355000  1967  TAVG  1000  1120  1290  1430  1810  1930  2390
16      10160355000  1968  TAVG  1090  1230  1300  1600  1810  2070  2470
17      10160355000  1969  TAVG  1170  1140  1340  1490  1820  1940  2230
18      10160355000  1970  TAVG  1290  1100  1220  1380  1650  2110  2320
19      10160355000  1971  TAVG  1160  1040  1050  1550  1830  2020  2380
20      10160355000  1972  TAVG  1010  1280  1410 -9999  1600  2040  2200
21      10160355000  1973  TAVG  1120  1010  1060  1360  1830  2160  2420
22      10160355000  1974  TAVG  1220  1180  1370  1340  1810  2160 -9999
23      10160355000  1975  TAVG  1150  1090  1190  1360  1670  1920  2400
24      10160355000  1976  TAVG  1020  1080  1180  1450 -9999 -9999 -9999
25      10160355000  1977  TAVG  1260  1290  1330  1480  1770  2030  2320
26      10160355000  1978  TAVG   990  1340 -9999  1380  1690  2060  2310
27      10160355000  1979  TAVG  1370  1280  1270  1300 -9999  2130  2350
28      10160355000  1980  TAVG  1080  1160  1240  1300  1630  2040  2210
29      10160355000  1981  TAVG   980  1090  1390  1580  1770  2090  2250
...             ...   ...   ...   ...   ...   ...   ...   ...   ...   ...
471035  80099912001  1980  TAVG   460   530   510   550   650   870  1110
471036  80099912001  1981  TAVG   710   600   560   560 -9999 -9999 -9999
471037  80099913001  1975  TAVG -9999 -9999 -9999 -9999 -9999 -9999  1680
471038  80099913001  1976  TAVG -9999  1090  1070  1100  1260  1530  1630
471039  80099913001  1977  TAVG  1010  1070  1070  1090  1230  1410  1640
471040  80099913001  1978  TAVG  1030  1100  1090  1080  1230  1340  1570
471041  80099913001  1979  TAVG  1040  1110  1080  1080  1170  1410  1770
471042  80099913001  1980  TAVG  1100  1100  1030  1110  1290  1440  1600
471043  80099913001  1981  TAVG  1210  1100  1180  1180  1200  1430  1690
471044  80099913001  1982  TAVG  1210 -9999  1120  1190  1260  1400  1400
471045  80099913001  1983  TAVG  1160  1050  1140  1000  1140  1450  1660
471046  80099913001  1984  TAVG  1100  1110  1010  1200  1210 -9999 -9999
471047  80099913001  1985  TAVG  1110  1110  1130  1140  1250  1420  1690
471048  80099914001  1955  TAVG -9999 -9999 -9999  1670  1880  2060  2430
471049  80099914001  1956  TAVG  1560  1460  1530  1590  1940  2050  2430
471050  80099914001  1957  TAVG  1370  1360  1370  1580  1640  1810  2240
471051  80099914001  1958  TAVG  1500  1370  1490  1590  1760  2100  2500
471052  80099914001  1959  TAVG  1550  1420  1370  1580  1840  1990  2280
471053  80099914001  1960  TAVG  1470  1410  1430  1660  1710  1930  2420
471054  80099914001  1961  TAVG  1460  1410  1410  1660  1780  2000  2490
471055  80099914001  1962  TAVG  1490  1410  1540  1590  1720  2190  2420
471056  80099914001  1963  TAVG  1580  1290  1430  1480  1710  1890  2310
471057  80099914001  1964  TAVG  1480  1230  1480  1630  1670  1920  2400
471058  80099914001  1965  TAVG  1420  1410  1560  1400  1720  1990 -9999
471059  80099914001  1966  TAVG  1430  1460  1490  1450  1760  2000 -9999
471060  80099914001  1967  TAVG  1520  1440  1370  1490  1580  1940  2440
471061  80099914001  1968  TAVG  1430  1230 -9999  1610  1740  1960  2390
471062  80099914001  1969  TAVG  1590  1510  1420  1640  1970  2070  2460
471063  80099914001  1970  TAVG  1410  1360  1230 -9999  1830  1970 -9999
471064  80099914001  1971  TAVG  1500  1280  1490  1650 -9999  2060  2320

          31    35    39    43    47
0       2680  2320  2680  1370  1150
1       2510  2240  1750  1450   900
2       2570  2290  2060  1570  1290
3       2600  2160  1930  1550  1060
4      -9999  2440 -9999 -9999 -9999
5      -9999 -9999  2160  1480  1130
6       2460  2120  1820  1470  1330
7      -9999  2280 -9999  1490  1250
8       2350  2340  1700  1410  1080
9       2470  2270  1960  1700  1100
10      2420  2270  1960  1560  1230
11      2420  2230  2000  1530  1250
12      2350  2220  1970  1450  1080
13     -9999 -9999 -9999 -9999 -9999
14     -9999 -9999 -9999  1330  1100
15      2550  2250  2010  1660  1070
16      2410  2230  1910  1620  1280
17      2410  2200  1850  1610  1080
18      2490  2330  1470  1480  1140
19      2710  2260  1860  1330  1120
20      2280  2100  1990  1540  1190
21      2460  2350  1870  1400  1210
22      2400  2230  1700  1410 -9999
23      2470  2350 -9999  1390  1180
24     -9999 -9999 -9999  1290  1280
25      2290  2070 -9999  1540  1240
26      2390  2170  1710  1280  1410
27      2400  2090  1910  1310  1170
28      2410  2240  1780  1550   990
29      2340  2290  2000  1460  1540
...      ...   ...   ...   ...   ...
471035  1350 -9999  1050   770   650
471036 -9999 -9999 -9999 -9999 -9999
471037  1750  1620  1520 -9999  1130
471038  1830  1670  1340  1220  1030
471039  1700  1710  1490  1280  1210
471040  1720  1780  1580  1400  1150
471041  1720  1710  1450  1370  1220
471042  1680  1620  1460  1290  1240
471043  1900  1740  1460  1430  1210
471044  1720  1670  1430  1200  1120
471045  1860  1660  1480  1410  1230
471046  1850  1800  1520  1220  1190
471047  1590 -9999  1550  1290  1250
471048  2570  2540  2430  2030  1700
471049  2570  2410  2240  2030  1490
471050  2460  2400  2180  1930  1840
471051  2560  2350  2250  2080  1690
471052  2510  2330  2010  1820  1740
471053  2510  2480  2380  1990  1760
471054  2620  2440  2240  2010  1590
471055  2560  2460  2310  2040  1690
471056 -9999  2450  2260  1940  1690
471057  2580  2530  2310  1940  1520
471058  2470  2560  2370  1960  1720
471059 -9999  2570  2310  1920  1690
471060  2600  2570  2370  1850  1700
471061  2530  2410  2440  1860  1720
471062  2510 -9999  2150  1830 -9999
471063  2590  2430  2250  1960  1650
471064  2320  2450  2210  2000  1700

[471065 rows x 15 columns]

In [7]:
#rename columns
df.columns = ['ID','year','type','jan','feb','mar','apr','may','jun','jul','aug','sep','oct','nov','dec']
print(df)

                 ID  year  type   jan   feb   mar   apr   may   jun   jul  \
0       10160355000  1878  TAVG   890   950  1110  1610  1980  2240  2490
1       10160355000  1879  TAVG  1180  1170  1220  1550  1560  2270  2400
2       10160355000  1880  TAVG   960  1110  1240  1520  1710  2070  2580
3       10160355000  1931  TAVG -9999   970 -9999 -9999  1850  2390 -9999
4       10160355000  1932  TAVG  1010   980 -9999  1420  1840 -9999  2290
5       10160355000  1933  TAVG -9999 -9999 -9999 -9999  1870 -9999 -9999
6       10160355000  1934  TAVG  1030   970  1190  1550  1760 -9999  2450
7       10160355000  1935  TAVG   860  1090  1220  1500 -9999  2150 -9999
8       10160355000  1936  TAVG  1310  1380  1360  1550  1320  1950  2370
9       10160355000  1937  TAVG  1200  1250  1450  1470 -9999  2200  2320
10      10160355000  1938  TAVG  1060   900  1100  1320  1680  2160  2390
11      10160355000  1939  TAVG  1280  1180  1160  1470  1550  2010  2390
12      10160355000  1940  TAVG  1110  1300  1430  1470  1740  2000  2250
13      10160355000  1941  TAVG  1150 -9999  1400  1570 -9999 -9999 -9999
14      10160355000  1966  TAVG -9999 -9999 -9999 -9999 -9999 -9999 -9999
15      10160355000  1967  TAVG  1000  1120  1290  1430  1810  1930  2390
16      10160355000  1968  TAVG  1090  1230  1300  1600  1810  2070  2470
17      10160355000  1969  TAVG  1170  1140  1340  1490  1820  1940  2230
18      10160355000  1970  TAVG  1290  1100  1220  1380  1650  2110  2320
19      10160355000  1971  TAVG  1160  1040  1050  1550  1830  2020  2380
20      10160355000  1972  TAVG  1010  1280  1410 -9999  1600  2040  2200
21      10160355000  1973  TAVG  1120  1010  1060  1360  1830  2160  2420
22      10160355000  1974  TAVG  1220  1180  1370  1340  1810  2160 -9999
23      10160355000  1975  TAVG  1150  1090  1190  1360  1670  1920  2400
24      10160355000  1976  TAVG  1020  1080  1180  1450 -9999 -9999 -9999
25      10160355000  1977  TAVG  1260  1290  1330  1480  1770  2030  2320
26      10160355000  1978  TAVG   990  1340 -9999  1380  1690  2060  2310
27      10160355000  1979  TAVG  1370  1280  1270  1300 -9999  2130  2350
28      10160355000  1980  TAVG  1080  1160  1240  1300  1630  2040  2210
29      10160355000  1981  TAVG   980  1090  1390  1580  1770  2090  2250
...             ...   ...   ...   ...   ...   ...   ...   ...   ...   ...
471035  80099912001  1980  TAVG   460   530   510   550   650   870  1110
471036  80099912001  1981  TAVG   710   600   560   560 -9999 -9999 -9999
471037  80099913001  1975  TAVG -9999 -9999 -9999 -9999 -9999 -9999  1680
471038  80099913001  1976  TAVG -9999  1090  1070  1100  1260  1530  1630
471039  80099913001  1977  TAVG  1010  1070  1070  1090  1230  1410  1640
471040  80099913001  1978  TAVG  1030  1100  1090  1080  1230  1340  1570
471041  80099913001  1979  TAVG  1040  1110  1080  1080  1170  1410  1770
471042  80099913001  1980  TAVG  1100  1100  1030  1110  1290  1440  1600
471043  80099913001  1981  TAVG  1210  1100  1180  1180  1200  1430  1690
471044  80099913001  1982  TAVG  1210 -9999  1120  1190  1260  1400  1400
471045  80099913001  1983  TAVG  1160  1050  1140  1000  1140  1450  1660
471046  80099913001  1984  TAVG  1100  1110  1010  1200  1210 -9999 -9999
471047  80099913001  1985  TAVG  1110  1110  1130  1140  1250  1420  1690
471048  80099914001  1955  TAVG -9999 -9999 -9999  1670  1880  2060  2430
471049  80099914001  1956  TAVG  1560  1460  1530  1590  1940  2050  2430
471050  80099914001  1957  TAVG  1370  1360  1370  1580  1640  1810  2240
471051  80099914001  1958  TAVG  1500  1370  1490  1590  1760  2100  2500
471052  80099914001  1959  TAVG  1550  1420  1370  1580  1840  1990  2280
471053  80099914001  1960  TAVG  1470  1410  1430  1660  1710  1930  2420
471054  80099914001  1961  TAVG  1460  1410  1410  1660  1780  2000  2490
471055  80099914001  1962  TAVG  1490  1410  1540  1590  1720  2190  2420
471056  80099914001  1963  TAVG  1580  1290  1430  1480  1710  1890  2310
471057  80099914001  1964  TAVG  1480  1230  1480  1630  1670  1920  2400
471058  80099914001  1965  TAVG  1420  1410  1560  1400  1720  1990 -9999
471059  80099914001  1966  TAVG  1430  1460  1490  1450  1760  2000 -9999
471060  80099914001  1967  TAVG  1520  1440  1370  1490  1580  1940  2440
471061  80099914001  1968  TAVG  1430  1230 -9999  1610  1740  1960  2390
471062  80099914001  1969  TAVG  1590  1510  1420  1640  1970  2070  2460
471063  80099914001  1970  TAVG  1410  1360  1230 -9999  1830  1970 -9999
471064  80099914001  1971  TAVG  1500  1280  1490  1650 -9999  2060  2320

         aug   sep   oct   nov   dec
0       2680  2320  2680  1370  1150
1       2510  2240  1750  1450   900
2       2570  2290  2060  1570  1290
3       2600  2160  1930  1550  1060
4      -9999  2440 -9999 -9999 -9999
5      -9999 -9999  2160  1480  1130
6       2460  2120  1820  1470  1330
7      -9999  2280 -9999  1490  1250
8       2350  2340  1700  1410  1080
9       2470  2270  1960  1700  1100
10      2420  2270  1960  1560  1230
11      2420  2230  2000  1530  1250
12      2350  2220  1970  1450  1080
13     -9999 -9999 -9999 -9999 -9999
14     -9999 -9999 -9999  1330  1100
15      2550  2250  2010  1660  1070
16      2410  2230  1910  1620  1280
17      2410  2200  1850  1610  1080
18      2490  2330  1470  1480  1140
19      2710  2260  1860  1330  1120
20      2280  2100  1990  1540  1190
21      2460  2350  1870  1400  1210
22      2400  2230  1700  1410 -9999
23      2470  2350 -9999  1390  1180
24     -9999 -9999 -9999  1290  1280
25      2290  2070 -9999  1540  1240
26      2390  2170  1710  1280  1410
27      2400  2090  1910  1310  1170
28      2410  2240  1780  1550   990
29      2340  2290  2000  1460  1540
...      ...   ...   ...   ...   ...
471035  1350 -9999  1050   770   650
471036 -9999 -9999 -9999 -9999 -9999
471037  1750  1620  1520 -9999  1130
471038  1830  1670  1340  1220  1030
471039  1700  1710  1490  1280  1210
471040  1720  1780  1580  1400  1150
471041  1720  1710  1450  1370  1220
471042  1680  1620  1460  1290  1240
471043  1900  1740  1460  1430  1210
471044  1720  1670  1430  1200  1120
471045  1860  1660  1480  1410  1230
471046  1850  1800  1520  1220  1190
471047  1590 -9999  1550  1290  1250
471048  2570  2540  2430  2030  1700
471049  2570  2410  2240  2030  1490
471050  2460  2400  2180  1930  1840
471051  2560  2350  2250  2080  1690
471052  2510  2330  2010  1820  1740
471053  2510  2480  2380  1990  1760
471054  2620  2440  2240  2010  1590
471055  2560  2460  2310  2040  1690
471056 -9999  2450  2260  1940  1690
471057  2580  2530  2310  1940  1520
471058  2470  2560  2370  1960  1720
471059 -9999  2570  2310  1920  1690
471060  2600  2570  2370  1850  1700
471061  2530  2410  2440  1860  1720
471062  2510 -9999  2150  1830 -9999
471063  2590  2430  2250  1960  1650
471064  2320  2450  2210  2000  1700

[471065 rows x 15 columns]

In [8]:
#checking each column data type
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 471065 entries, 0 to 471064
Data columns (total 15 columns):
ID      471065 non-null int64
year    471065 non-null int64
type    471065 non-null object
jan     471065 non-null int64
feb     471065 non-null int64
mar     471065 non-null int64
apr     471065 non-null int64
may     471065 non-null int64
jun     471065 non-null int64
jul     471065 non-null int64
aug     471065 non-null int64
sep     471065 non-null int64
oct     471065 non-null int64
nov     471065 non-null int64
dec     471065 non-null int64
dtypes: int64(14), object(1)
memory usage: 53.9+ MB

In [9]:
#conver ID column from int to string type
df['ID'] = df['ID'].apply(str)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 471065 entries, 0 to 471064
Data columns (total 15 columns):
ID      471065 non-null object
year    471065 non-null int64
type    471065 non-null object
jan     471065 non-null int64
feb     471065 non-null int64
mar     471065 non-null int64
apr     471065 non-null int64
may     471065 non-null int64
jun     471065 non-null int64
jul     471065 non-null int64
aug     471065 non-null int64
sep     471065 non-null int64
oct     471065 non-null int64
nov     471065 non-null int64
dec     471065 non-null int64
dtypes: int64(13), object(2)
memory usage: 53.9+ MB

In [13]:
df.to_csv("../data/cleanedtempfile.csv", encoding='utf-8')

In [14]:
df.describe()

,year,jan,feb,mar,apr,may,jun,jul,aug,sep,oct,nov,dec
count,471065.000000,471065.000000,471065.000000,471065.000000,471065.000000,471065.000000,471065.000000,471065.000000,471065.000000,471065.000000,471065.000000,471065.000000,471065.000000
mean,1957.450910,-156.504064,7.181465,338.915653,764.394258,1116.473983,1419.265288,1576.315046,1538.412650,1281.211996,875.513986,365.997306,-88.973216
std,37.247805,2630.311310,2559.034029,2513.994700,2445.893605,2479.912305,2509.947050,2583.811270,2565.248193,2500.808766,2468.292954,2539.823063,2705.619401
min,1701.000000,-9999.000000,-9999.000000,-9999.000000,-9999.000000,-9999.000000,-9999.000000,-9999.000000,-9999.000000,-9999.000000,-9999.000000,-9999.000000,-9999.000000
25%,1935.000000,-709.000000,-544.000000,-40.000000,613.000000,1120.000000,1440.000000,1670.000000,1593.000000,1290.000000,796.000000,120.000000,-480.000000
50%,1963.000000,136.000000,290.000000,660.000000,1142.000000,1540.000000,1920.000000,2174.000000,2106.000000,1750.000000,1286.000000,710.000000,260.000000
75%,1984.000000,1250.000000,1380.000000,1606.000000,1760.000000,2038.000000,2390.000000,2580.000000,2550.000000,2280.000000,1870.000000,1570.000000,1310.000000
max,2018.000000,7600.000000,8690.000000,8720.000000,8780.000000,6040.000000,9000.000000,15440.000000,6490.000000,9000.000000,8800.000000,8600.000000,9990.000000